name: Test Report

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

jobs:
  test-report:
    name: Test report
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: sz.de/jobs Monitoring
          path: '*.xml'
          reporter: jest-junit
          fail-on-error: 'false'
